### ISSUE TITLE
Unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mwwilson** [Educorreia932/Character-Sheet#1]
When cloning and running the repository on OSX, the following error appears: "unrecognized selector sent to instance"

This is due to the TkAgg property not being explicitly set for OSX machines, solution found here: https://stackoverflow.com/questions/32019556/matplotlib-crashing-tkinter-application/34109240#34109240

**Comment by mwwilson** [comment]
#2 fixes this issue. Made the change and was able to run the script locally. It's super fun to play with. Cheers!

**Comment by Educorreia932** [comment]
Thank you! :)
